### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jchristgit** [jb3/jeeves#1]
Hello,

I have a question. Why didn't you use Erlang? Erlang is a web scale language, and doesn't use GILs or mutability, so it's [high-performance](https://www.erlang.org/blog/the-road-to-the-jit/).

**Comment by NicholasG04** [comment]
@jb3 - I'd be really interested to hear more about this choice, too. Thanks for raising it @jchristgit.

**Comment by Dennisschu** [comment]
Yea why not Erlang? Python is such a slow language

**Comment by jb3** [comment]
Thank you for voicing your concerns.
