### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by NicholasG04** [jb3/jeeves#2]
Hello Mr Banks. I was perusing the codebase available hereto, and noticed a lack of web scale technologies. Please could you inform me of the reasons for which you chose to use legacy technology (such as Python) in lieu of web scale technology such as TypeScript and MongoDB. 

With my distinguished sentiments,
Nick

**Comment by RealJammy** [comment]
Do you know when an update to this will be provided? Web scale technology is an integral part in making high quality programs.

I notice that a previous issue was closed, as signified by the below artists impression: 
![1984](https://user-images.githubusercontent.com/57639251/159570132-f185bcdb-bc78-47b2-8f96-7e4d4883a0a6.png)

To improve your code, I strongly recommend being able to take on valid criticisms, and implement these into your code where necessary.
